name: Hello world

on:
  push:
    branches:
      - 'main'
  pull_request:
      branches:
        - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
        with:
          name: code-coverage-report
          path: code-coverage.html



